before_script: 
    - apt install virtualenv
    - virtualenv venv3 -p python3
    - source venv3/bin/activate
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt

run:
    script:
        - make test
